### ISSUE TITLE
dll js reference issue

### ISSUE THREAD

**Issue by ghost** [NZMia/NZMia.github.io-old#3]
found one issue about dll js reference.
In src/index.html, there is a hardcode reference of vender.dll.js file. However after 'npm run dll' command called the hash will change (I guess it's machine related) then the reference broken. 

to fix it:

- remove hardcode reference of vender.dll.js in src/index.html
- add add-asset-html-webpack-plugin package
- setup the plugin in order to dynamically inject vender.dll.js to index.html at compile time

note: when using a fresh copy of source code, cross-env package will be required in devDependencies to execute any command e.g. npm run build

**Comment by NZMia** [comment]
Fixed issue that `DLL` file inject not dynamically during the compile process.
